packages:
  - 'cli/'
  - 'extension/'
  - 'src/'
  - 'src/wirestate-core'
  - 'src/wirestate-dev'
  - 'src/wirestate-lit'
  - 'src/wirestate-lit-mobx'
  - 'src/wirestate-lit-signals'
  - 'src/wirestate-mobx'
  - 'src/wirestate-react'
  - 'src/wirestate-react-mobx'
  - 'src/wirestate-react-signals'
  - 'src/wirestate-signals'

autoInstallPeers: false

allowBuilds:
  '@swc/core': true
  core-js: true
  esbuild: true
  unrs-resolver: true

overrides:
  '@types/react': 19.2.18
  '@types/react-dom': 19.2.4
  react: 19.2.8
  react-dom: 19.2.8

minimumReleaseAge: 1440 # minutes (1 day)
minimumReleaseAgeExclude:
  - '@wirestate/*'
  - rolldown
  - '@rolldown/*'
  - '@napi-rs/wasm-runtime'
