export const ERROR_CODE_CIRCULAR_DEPENDENCY: string = "CIRCULAR_DEPENDENCY";
export const ERROR_CODE_FAILED_TO_RESOLVE_COMMAND_HANDLER: string = "FAILED_TO_RESOLVE_COMMAND_HANDLER";
export const ERROR_CODE_FAILED_TO_RESOLVE_QUERY_HANDLER: string = "FAILED_TO_RESOLVE_QUERY_HANDLER";
export const ERROR_CODE_GENERIC: string = "GENERIC";
export const ERROR_CODE_INVALID_ARGUMENTS: string = "INVALID_ARGUMENTS";
export const ERROR_CODE_INVALID_BINDING_SCOPE: string = "INVALID_BINDING_SCOPE";
export const ERROR_CODE_NO_BINDING_FOUND: string = "NO_BINDING_FOUND";
export const ERROR_CODE_VALIDATION_ERROR: string = "VALIDATION_ERROR";
