import {
  ERROR_CODE_CIRCULAR_DEPENDENCY,
  ERROR_CODE_FAILED_TO_RESOLVE_COMMAND_HANDLER,
  ERROR_CODE_FAILED_TO_RESOLVE_QUERY_HANDLER,
  ERROR_CODE_GENERIC,
  ERROR_CODE_INVALID_ARGUMENTS,
  ERROR_CODE_INVALID_BINDING_SCOPE,
  ERROR_CODE_NOT_TRACKED,
  ERROR_CODE_NO_BINDING_FOUND,
  ERROR_CODE_NO_INJECTION_CONTEXT,
  ERROR_CODE_UNKNOWN_BINDING_TYPE,
  ERROR_CODE_VALIDATION_ERROR,
} from "./error-code";

describe("@wirestate/core error codes", () => {
  it("should pin the exact public string values", () => {
    expect({
      ERROR_CODE_CIRCULAR_DEPENDENCY,
      ERROR_CODE_FAILED_TO_RESOLVE_COMMAND_HANDLER,
      ERROR_CODE_FAILED_TO_RESOLVE_QUERY_HANDLER,
      ERROR_CODE_GENERIC,
      ERROR_CODE_INVALID_ARGUMENTS,
      ERROR_CODE_INVALID_BINDING_SCOPE,
      ERROR_CODE_NOT_TRACKED,
      ERROR_CODE_NO_BINDING_FOUND,
      ERROR_CODE_NO_INJECTION_CONTEXT,
      ERROR_CODE_UNKNOWN_BINDING_TYPE,
      ERROR_CODE_VALIDATION_ERROR,
    }).toEqual({
      ERROR_CODE_CIRCULAR_DEPENDENCY: "CORE_CIRCULAR_DEPENDENCY",
      ERROR_CODE_FAILED_TO_RESOLVE_COMMAND_HANDLER: "CORE_FAILED_TO_RESOLVE_COMMAND_HANDLER",
      ERROR_CODE_FAILED_TO_RESOLVE_QUERY_HANDLER: "CORE_FAILED_TO_RESOLVE_QUERY_HANDLER",
      ERROR_CODE_GENERIC: "CORE_GENERIC",
      ERROR_CODE_INVALID_ARGUMENTS: "CORE_INVALID_ARGUMENTS",
      ERROR_CODE_INVALID_BINDING_SCOPE: "CORE_INVALID_BINDING_SCOPE",
      ERROR_CODE_NOT_TRACKED: "CORE_NOT_TRACKED",
      ERROR_CODE_NO_BINDING_FOUND: "CORE_NO_BINDING_FOUND",
      ERROR_CODE_NO_INJECTION_CONTEXT: "CORE_NO_INJECTION_CONTEXT",
      ERROR_CODE_UNKNOWN_BINDING_TYPE: "CORE_UNKNOWN_BINDING_TYPE",
      ERROR_CODE_VALIDATION_ERROR: "CORE_VALIDATION_ERROR",
    });
  });

  it("should prefix every core error code with the CORE_ origin tag", () => {
    const codes: Array<string> = [
      ERROR_CODE_CIRCULAR_DEPENDENCY,
      ERROR_CODE_FAILED_TO_RESOLVE_COMMAND_HANDLER,
      ERROR_CODE_FAILED_TO_RESOLVE_QUERY_HANDLER,
      ERROR_CODE_GENERIC,
      ERROR_CODE_INVALID_ARGUMENTS,
      ERROR_CODE_INVALID_BINDING_SCOPE,
      ERROR_CODE_NOT_TRACKED,
      ERROR_CODE_NO_BINDING_FOUND,
      ERROR_CODE_NO_INJECTION_CONTEXT,
      ERROR_CODE_UNKNOWN_BINDING_TYPE,
      ERROR_CODE_VALIDATION_ERROR,
    ];

    for (const code of codes) {
      expect(code).toMatch(/^CORE_/);
    }
  });
});
