import { assertExportedApi } from "#/test/exported-api.utils";

describe("Library exported API from wirestate-core", () => {
  it("should export exactly the documented core API surface", () => {
    assertExportedApi(require.resolve("./index"), {
      values: [
        "BindingScope",
        "BindingType",
        "CommandBus",
        "CommandsPlugin",
        "Container",
        "EventBus",
        "EventsPlugin",
        "Injectable",
        "InjectionToken",
        "OnActivated",
        "OnCommand",
        "OnDeactivation",
        "OnDeprovision",
        "OnEvent",
        "OnProvision",
        "OnQuery",
        "QueriesPlugin",
        "QueryBus",
        "WireStatus",
        "WirestateError",
        "defaultInternalErrorHandler",
        "inject",
        "isInjectable",
        "validateContainerConfig",
      ],
      types: [
        "Binding",
        "BindingDescriptor",
        "CommandDispatchOptions",
        "CommandHandler",
        "CommandType",
        "CommandUnregister",
        "ContainerConfig",
        "EventEmitOptions",
        "EventHandler",
        "EventType",
        "EventUnsubscribe",
        "FactoryBindingDescriptor",
        "InstanceBindingDescriptor",
        "InternalErrorDescriptor",
        "InternalErrorHandler",
        "InternalErrorSource",
        "Newable",
        "OnCommandHandlerDecorator",
        "OnEventHandlerDecorator",
        "OnQueryHandlerDecorator",
        "ProvisionId",
        "QueryDispatchOptions",
        "QueryHandler",
        "QueryType",
        "QueryUnregister",
        "ServiceToken",
        "ValueBindingDescriptor",
        "WireEvent",
        "WirestatePlugin",
      ],
    });
  });
});
