describe("Library exported API from wirestate/react-mobx", () => {
  const libRoot = require("./index");

  const expectedLibExports: Array<string> = [
    "$mobx",
    "Action",
    "AnnotationMapEntry",
    "AnnotationsMap",
    "Computed",
    "CreateObservableOptions",
    "DeepObservable",
    "FlowCancellationError",
    "IActionFactory",
    "IActionRunInfo",
    "IArrayDidChange",
    "IArraySplice",
    "IArrayUpdate",
    "IArrayWillChange",
    "IArrayWillSplice",
    "IAtom",
    "IAutorunOptions",
    "IComputedFactory",
    "IComputedValue",
    "IComputedValueOptions",
    "IDepTreeNode",
    "IDependencyTree",
    "IEnhancer",
    "IEqualsComparer",
    "IInterceptable",
    "IInterceptor",
    "IKeyValueMap",
    "IListenable",
    "IMapDidChange",
    "IMapEntries",
    "IMapEntry",
    "IMapWillChange",
    "IObjectDidChange",
    "IObjectWillChange",
    "IObservable",
    "IObservableArray",
    "IObservableFactory",
    "IObservableMapInitialValues",
    "IObservableSetInitialValues",
    "IObservableValue",
    "IObserverTree",
    "IReactionDisposer",
    "IReactionOptions",
    "IReactionPublic",
    "ISetDidChange",
    "ISetWillChange",
    "IValueDidChange",
    "IValueWillChange",
    "IWhenOptions",
    "Lambda",
    "Observable",
    "ObservableMap",
    "ObservableSet",
    "Observer",
    "Reaction",
    "RefObservable",
    "ShallowObservable",
    "autorun",
    "clearTimers",
    "comparer",
    "configure",
    "createAtom",
    "enableStaticRendering",
    "entries",
    "extendObservable",
    "flow",
    "flowResult",
    "get",
    "getAtom",
    "getDebugName",
    "getDependencyTree",
    "getObserverTree",
    "has",
    "intercept",
    "isAction",
    "isBoxedObservable",
    "isComputed",
    "isComputedProp",
    "isFlow",
    "isFlowCancellationError",
    "isObservable",
    "isObservableArray",
    "isObservableMap",
    "isObservableObject",
    "isObservableProp",
    "isObservableSet",
    "isObserverBatched",
    "isUsingStaticRendering",
    "keys",
    "makeAutoObservable",
    "makeObservable",
    "observe",
    "observer",
    "observerBatching",
    "onBecomeObserved",
    "onBecomeUnobserved",
    "onReactionError",
    "override",
    "reaction",
    "remove",
    "runInAction",
    "set",
    "spy",
    "toJS",
    "trace",
    "transaction",
    "untracked",
    "useAsObservableSource",
    "useLocalObservable",
    "useLocalStore",
    "useObserver",
    "values",
    "when",
  ];

  const assertListIntersection = (first: Array<string>, second: Array<string>) => {
    first.forEach((it: string) => {
      if (!second.includes(it)) {
        throw new Error("Item missing in expected list: " + it);
      }
    });
    second.forEach((it: string) => {
      if (!first.includes(it)) {
        throw new Error("Item missing in library root: " + it);
      }
    });
  };

  it("should export correct core API methods", () => {
    assertListIntersection(Object.keys(libRoot), expectedLibExports);
    expect(Object.keys(libRoot)).toHaveLength(expectedLibExports.length);
  });
});
